### ISSUE TITLE
Newest version deleted my minecraft world... :(

### ISSUE THREAD

**Issue by Esc0rtd** [Wurmcraft/Sever-Essentials-2#4]
Newest version deleted my minecraft world... :( this is bad virus

**Comment by Wurmatron** [comment]
Unsure how this would even be possible, the only "files" that Server Essentials can delete, Would be under the /DeletePlayerFile command which even when it deletes a given file its copied into another folder `Server Essentials/Deleted` just in case, however this must be in the world's `playerdata` folder and ended with a `.dat`, which i dont think even a world backup would have.

https://github.com/Wurmcraft/Server-Essentials/blob/e68bde8bfd29efa34a66e47f78ff938423a7f070/1.12.2-Forge/src/main/java/com/wurmcraft/serveressentials/common/modules/general/command/admin/DeletePlayerFileCommand.java#L92

**Comment by Wurmatron** [comment]
As it seems you use Github a lot, I do implore you,Look at the code, and see if you can find this, as it would be a very strange bug, and would need to be fixed ASAP. However as the main part of this codebase is 5+ years old without issues, it seems strange that it would pop up now.

**Comment by Esc0rtd** [comment]
I dont think this case is closed, because you deleted my minecraft world, and i think you will need to fix the code .

**Comment by Wurmatron** [comment]
Do you have any more information to provide? besides "it deleted my world, this needs to be fixed"

What were you doing to cause this? 
which version (exact)? 
What modules were enabled?
How where you running the server? 
What OS? Version?

I'm a single developer, doing this in my free time I don't have time to deal with tracking down, nearly impossible bugs without any kind of proof and or information to even attempt to find them. Without any kind of information or proof that its real or how to recreate it, This issue will stay closed.
